spring.application.name=PlateformeElearning
spring.datasource.url=jdbc:mysql://localhost:3306/Elearning_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.upload.dir=uploads/